[package]
name = "grift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A simple minimalistic Lisp built on the grift_arena allocator"

[features]
repl = ["dep:rustyline"]

[dependencies]
grift_arena.workspace = true
grift_macros = { path = "../grift_macros" }
rustyline = { version = "17.0.2", optional = true }

[[bin]]
name = "grift"
required-features = ["repl"]
