[package]
name = "grift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A simple minimalistic Lisp built on the grift_arena allocator"

[features]
repl = ["dep:rustyline"]

[dependencies]
grift_arena.workspace = true
grift_macros = { path = "../grift_macros" }
rustyline = { version = "17.0.2", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bin]]
name = "grift"
required-features = ["repl"]

[[bench]]
name = "eval_bench"
harness = false
